from functools import lru_cache

# Based on SIMBAD object types, https://vizier.cds.unistra.fr/cgi-bin/OType?$1
# AB - 16/03/2026

GENERAL_GROUPS = {
    # Stars
    "Ma*": "star",
    "bC*": "star",
    "sg*": "star",
    "s*r": "star",
    "s*y": "star",
    "s*b": "star",
    "WR*": "star",
    "N*": "star",
    "Psr": "star",
    "Y*O": "star",
    "Or*": "star",
    "TT*": "star",
    "Ae*": "star",
    "out": "star",
    "HH": "star",
    "MS*": "star",
    "Be*": "star",
    "BS*": "star",
    "SX*": "star",
    "gD*": "star",
    "dS*": "star",
    "Ev*": "star",
    "RG*": "star",
    "HS*": "star",
    "HB*": "star",
    "RR*": "star",
    "WV*": "star",
    "Ce*": "star",
    "cC*": "star",
    "C*": "star",
    "S*": "star",
    "LP*": "star",
    "AB*": "star",
    "Mi*": "star",
    "OH*": "star",
    "pA*": "star",
    "RV*": "star",
    "WD*": "star",
    "Pe*": "star",
    "a2*": "star",
    "RC*": "star",
    "**": "star",
    "El*": "star",
    "EB*": "star",
    "SB*": "star",
    "BY*": "star",
    "RS*": "star",
    "Sy*": "star",
    "XB*": "star",
    "LXB": "star",
    "HXB": "star",
    "CV*": "star",
    "No*": "star",
    "LM*": "star",
    "BD*": "star",
    "V*": "star",
    "Ir*": "star",
    "Er*": "star",
    "Ro*": "star",
    "Pu*": "star",
    "Em*": "star",
    "PM*": "star",
    "HV*": "star",
    # Planet
    "Pl": "planet",
    # Star clusters
    "Cl*": "star cluster",
    "GlC": "star cluster",
    "OpC": "star cluster",
    "As*": "star cluster",
    "St*": "star cluster",
    "MGr": "star cluster",
    # Galaxies
    "G": "galaxies",
    "LSB": "galaxies",
    "bCG": "galaxies",
    "SBG": "galaxies",
    "H2G": "galaxies",
    "EmG": "galaxies",
    "AGN": "galaxies",
    "SyG": "galaxies",
    "Sy1": "galaxies",
    "Sy2": "galaxies",
    "rG": "galaxies",
    "LIN": "galaxies",
    "QSO": "galaxies",
    "Bla": "galaxies",
    "BLL": "galaxies",
    # Sets of galaxies
    "IG": "galaxies set",
    "PaG": "galaxies set",
    "GrG": "galaxies set",
    "CGG": "galaxies set",
    "ClG": "galaxies set",
    "PCG": "galaxies set",
    "SCG": "galaxies set",
    "vid": "galaxies set",
    "GiP": "galaxies set",
    "GiG": "galaxies set",
    "GiC": "galaxies set",
    "BiC": "galaxies set",
    # Spectral sources
    "ev": "spectral source",
    "var": "spectral source",
    "Rad": "spectral source",
    "mR": "spectral source",
    "cm": "spectral source",
    "mm": "spectral source",
    "smm": "spectral source",
    "HI": "spectral source",
    "rB": "spectral source",
    "Mas": "spectral source",
    "IR": "spectral source",
    "FIR": "spectral source",
    "MIR": "spectral source",
    "NIR": "spectral source",
    "Opt": "spectral source",
    "EmO": "spectral source",
    "blu": "spectral source",
    "UV": "spectral source",
    "X": "spectral source",
    "ULX": "spectral source",
    "gam": "spectral source",
    "gB": "spectral source",
    # Nebulae
    "GNe": "nebula",
    "RNe": "nebula",
    "HII": "nebula",
    # Clouds
    "Cld": "cloud",
    "MoC": "cloud",
    "DNe": "cloud",
    "glb": "cloud",
    "CGb": "cloud",
    "HVC": "cloud",
    "cor": "cloud",
    "bub": "cloud",
    "sh": "cloud",
    "flt": "cloud",
}


@lru_cache(maxsize=None)
def map_to_group(otype: str) -> str:
    """
    Map any SIMBAD object type to one of the 8 general groups.
    Returns 'Default' for unrecognized types.
    """
    return GENERAL_GROUPS.get(otype, "Default")
