@startuml class
skinparam classAttributeIconSize 0

class FastAPIApp {
    +run_processing(req: ProcessRequest)
    +health()
    +catalog()
}

class Pipeline {
    -processors: Dict<String, IProcessor>
    -metrics: Metrics
    +run(fits_path: Path, selected: List<String>, output_dir: Path) : Dict
}

class Metrics {
    -total_time: float
    -count: int
    +register(duration: float)
    +average_time() : float
}

package Core {

	interface IProcessor {
		+name() : str
		+run(image, header, output_dir: Path) : dict
	}

	class ProcessRequest {
		-fits_file: str
		-processors: List<String>
	}
}

package Processors {
	class StarDetectionProcessor {
		+name() : str
		+run(image, header, output_dir: Path) : dict
	}

	class FitsToPngProcessor {
		+name() : str
		+run(image, header, output_dir: Path) : dict
	}
}



FastAPIApp --> Pipeline
Pipeline --> IProcessor : uses
IProcessor <|-- StarDetectionProcessor
IProcessor <|-- FitsToPngProcessor
Pipeline --> Metrics : uses
FastAPIApp --> ProcessRequest : accepts

@enduml